### ISSUE TITLE
p-retry returns attempt  count instead of resolved promise value

### ISSUE THREAD

**Issue by ChavaSobreyra** [sindresorhus/p-retry#9] opened 2018-07-07 22:55 UTC
i'm getting back the attempt count instead of the input promise's resolved value.

is this expected behavior?
```
const result = await pRetry(myPromise(data), { retries: 5 })

console.log(result) // 1
```

**Comment by acostalima** [comment] 2018-07-13 20:23
Looking at the source, it appears the promise resolves with the return value of the `input` promise.

**Comment by acostalima** [comment] 2018-07-13 21:13
Actually, I think the problem is that `myPromise(data)`, which is returning `undefined`, is being called as soon as your script is evaluated. So, the above will become:

```
const result = await pRetry(undefined, { retries: 5 })
```

If you pass `undefined` to `then`, the return value of the previous promise is propagated through the chain. In this case, `attemptNumber` is returned as you observed.

Can you confirm this?

**Comment by acostalima** [comment] 2018-07-24 22:14
@sindresorhus I think you can close this since the behavior reported is due to misuse.

**Closed** 2018-07-24 22:43 UTC

**Comment by ChavaSobreyra** [comment] 2018-07-25 02:09
thank you @acostalima
