### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by sagimann** [sindresorhus/p-retry#62] opened 2022-03-25 13:53 UTC
While trying to use p-retry in a TypeScript project, from within a Jest test, I'm getting the following full error output:
```
$ npm t

> jest2@1.0.0 test /Users/xxxx/xxx/jest2
> jest

 FAIL  ./sum.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/xxxx/xxxx/jest2/node_modules/p-retry/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import retry from 'retry';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import pRetry from 'p-retry';
        | ^
      2 |
      3 | export function sum(a: number, b: number): number {
      4 |     pRetry(async () => { return Promise.resolve() });

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (sum.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.659 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

It doesn't happen with other modules, like Axios, for example.
Tested with p-retry 5.1.0, Node 16.14.2, observe the error while running `npm test`
See attached sample project
[sample.zip](https://github.com/sindresorhus/p-retry/files/8351053/sample.zip)

**Comment by sindresorhus** [comment] 2022-03-25 15:37
Duplicate of #57

**Closed by sindresorhus** 2022-03-25 15:37 UTC

**Comment by MichaelTrosin** [comment] 2026-01-01 09:20
As a workaround if you can't fully move to ESM, you can add this to `jest.config.js`:

```
  moduleNameMapper: {
    "^p-retry$": "<rootDir>/src/__mocks__/p-retry.ts",
  },
```

and have a super-barebone `pRetry` method in that mock file.
